### PR TITLE
Add rustfmt.toml with hard_tabs set to true & run cargo fmt

### PR DESCRIPTION
**Pull request by Atul9**

### CODE REVIEW

**Comment by takahirox** [comment]
Thanks for the PR! I'm still new to Rust. This type of standardization is very helpful.

According to the diff on GitHub, you seemed to update every line in `src/main.rs` although it doesn't look so different. What is the main change in that file? New line code?

**Comment by Atul9** [comment]
I just ran `cargo fmt`, I didn't change anything using an editor.

**Comment by takahirox** [comment]
We don't need to manually edit the source code files. Good to know that.

Would you mind if having only `rustfmt.toml` file in this PR? I have been locally working on [Linux boot on the emulator](https://twitter.com/superhoge/status/1243105817655566337) and it may change a lot of codes. So the formatted files in this current PR may give a huge conflicts with mine.

Then I'd like to `run cargo fmt` in my side after I merge the change for Linux boot.

**Comment by Atul9** [comment]
@takahirox done, I have updated the PR

**Comment by takahirox** [comment]
Thanks!

**Pull request merged**
